djangogramm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", home_view, name="home-view"),
    path('accounts/', include('allauth.urls')),
    path("profiles/", include("profiles.urls", namespace="profiles")),
    path("posts/", include("posts.urls", namespace="posts")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

posts/urls.py
from django.urls import path
from .views import (post_comment_create_and_list_view, like_dislike_posts,
                    PostDeleteView, PostUpdateView, posts_of_following_profiles)


app_name = "posts"
urlpatterns = [
    path("", post_comment_create_and_list_view, name="main-post-view"),
    path("following/", posts_of_following_profiles, name="follow-post-view"),
    path("liked/", like_dislike_posts, name="like-post-view"),
    path("<pk>/delete/", PostDeleteView.as_view(), name="post-delete"),
    path("<pk>/update/", PostUpdateView.as_view(), name="post-update"),
]

profiles/urls.py
from django.urls import path
from .views import (
    my_profile_view, invites_received_view, invite_profiles_list_view, ProfilesListView, follow_unfollow_profile,
    ProfilesDetailView, send_invitation, accept_invitation, reject_invitation, remove_from_friends, profile_subs_view,
    search_result
)


app_name = "profiles"

urlpatterns = [
    path("", ProfilesListView.as_view(), name="all-profiles-view"),
    path("search/", search_result, name="search"),
    path("myprofile/", my_profile_view, name="my-profile-view"),
    path("my-invites/", invites_received_view, name="my-invites-view"),
    path("to-invite/", invite_profiles_list_view, name="invite-profiles-view"),
    path("send-invite/", send_invitation, name="send-invite"),
    path("remove-friend/", remove_from_friends, name="remove-friend"),
    path("switch_follow/", follow_unfollow_profile, name="follow-unfollow-view"),
    path("my-subscriptions/", profile_subs_view, name="my-subscriptions"),
    path("<slug>/", ProfilesDetailView.as_view(), name="profiles-detail-view"),
    path("my-invites/accept/", accept_invitation, name="accept-invite"),
    path("my-invites/reject/", reject_invitation, name="reject-invite"),
]

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from .utils import get_uid
from django.template.defaultfilters import slugify
from django.db.models import Q
from django.shortcuts import reverse


class ProfileManager(models.Manager):

    def get_all_profiles_to_invite(self, sender):
        profiles = Profile.objects.all().exclude(user=sender)
        profile = Profile.objects.get(user=sender)
        q_set = Relationship.objects.filter(Q(sender=profile) | Q(receiver=profile))
        accepted = set([])
        for rel_ship in q_set:
            if rel_ship.status == "accepted":
                accepted.add(rel_ship.receiver)
                accepted.add(rel_ship.sender)
        available = [profile for profile in profiles if profile not in accepted]
        return available

    def get_all_profiles(self, me):  # !!!
        profiles = Profile.objects.all().exclude(user=me)
        return profiles


class Profile(models.Model):
    first_name = models.CharField(max_length=100, blank=True)
    last_name = models.CharField(max_length=100, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(default="Bio is not completed...", max_length=400)
    country = models.CharField(max_length=100, blank=True)
    avatar = models.ImageField(default="avatar.png", upload_to="avatars/")
    following = models.ManyToManyField(User, blank=True, related_name="following")
    friends = models.ManyToManyField(User, blank=True, related_name="friends")
    slug = models.SlugField(unique=True, blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    objects = ProfileManager()

    def __str__(self):
        return f"{self.user}-{self.created.strftime('%d-%m-%Y')}"

    def get_absolute_url(self):
        return reverse("profiles:profiles-detail-view", kwargs={"slug": self.slug})

    def get_friends(self):
        return self.friends.all()

    def get_followers(self):
        return self.following.all()

    def get_friends_number(self):
        return self.friends.all().count()

    def get_post_no(self):
        return self.posts.all().count()

    def get_all_authors_posts(self):
        return self.posts.all()

    def get_likes_given_no(self):
        likes = self.like_set.all()
        total_liked = 0
        for like in likes:
            if like.value == "like":
                total_liked += 1
        return total_liked

    def get_likes_received_no(self):
        posts = self.posts.all()
        total_liked = 0
        for like in posts:
            total_liked += like.liked.all().count()
        return total_liked

    __initial_first_name = None
    __initial_last_name = None

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.__initial_first_name = self.first_name
        self.__initial_last_name = self.last_name

    def save(self, *args, **kwargs):
        exist = False
        to_slug = self.slug
        if self.first_name != self.__initial_first_name or self.last_name != self.__initial_last_name or self.slug == "":
            if self.first_name and self.last_name:
                to_slug = slugify(str(self.first_name) + " " + str(self.last_name))
                exist = Profile.objects.filter(slug=to_slug).exists()
                while exist:
                    to_slug = slugify(to_slug + " " + str(get_uid()))
                    exist = Profile.objects.filter(slug=to_slug).exists()
            else:
                to_slug = str(self.user)
        self.slug = to_slug
        super().save(*args, **kwargs)


STATUS_CHOICES = (
    ("send", "send"),
    ("accepted", "accepted")
)


class RelationshipManager(models.Manager):  # !!!

    def invitations_received(self, receiver):
        q_set = Relationship.objects.filter(receiver=receiver, status="send")
        return q_set


class Relationship(models.Model):  # !!!
    sender = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="sender")
    receiver = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="receiver")
    status = models.CharField(max_length=10, choices=STATUS_CHOICES)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    objects = RelationshipManager()  # !!!

    def __str__(self):
        return f"{self.sender}, {self.receiver}, {self.status} at {self.updated.strftime('%d-%m-%Y - %H:%M')}"

profiles/forms.py
from django import forms
from .models import Profile


class ProfileModelForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ("first_name", "last_name", "bio", "country", "avatar")

profiles/views.py
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from .models import Profile, Relationship
from .forms import ProfileModelForm
from django.views.generic import ListView, DetailView
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse



@login_required()
def my_profile_view(request):
    profile = Profile.objects.get(user=request.user)
    form = ProfileModelForm(request.POST or None, request.FILES or None, instance=profile)
    confirm = False
    if request.method == "POST":
        if form.is_valid():
            form.save()
            confirm = True
    context = {
        "profile": profile,
        "form": form,
        "confirm": confirm,
    }
    return render(request, "profiles/myprofile.html", context)


@login_required()
def invites_received_view(request):
    profile = Profile.objects.get(user=request.user)
    q_set = Relationship.objects.invitations_received(profile)
    results = list(map(lambda x: x.sender, q_set))
    is_empty = False
    if len(results) == 0:
        is_empty = True
    context = {
        "q_set": results,
        "is_empty": is_empty,
    }
    return render(request, "profiles/my_invites.html", context)


@login_required()
def accept_invitation(request):
    if request.method == "POST":
        pk = request.POST.get("profile_pk")
        sender = Profile.objects.get(pk=pk)
        receiver = Profile.objects.get(user=request.user)
        rel = get_object_or_404(Relationship, sender=sender, receiver=receiver)
        if rel.status == "send":
            rel.status = "accepted"
            rel.save()
    return redirect("profiles:my-invites-view")


@login_required()
def reject_invitation(request):
    if request.method == "POST":
        pk = request.POST.get("profile_pk")
        sender = Profile.objects.get(pk=pk)
        receiver = Profile.objects.get(user=request.user)
        rel = get_object_or_404(Relationship, sender=sender, receiver=receiver)
        rel.delete()
    return redirect("profiles:my-invites-view")


@login_required()
def invite_profiles_list_view(request):
    user = request.user
    q_set = Profile.objects.get_all_profiles_to_invite(user)
    context = {
        "q_set": q_set,
    }
    return render(request, "profiles/to_invite_list.html", context)


@login_required()
def profiles_list_view(request):
    user = request.user
    q_set = Profile.objects.get_all_profiles(user)
    context = {
        "q_set": q_set,
    }
    return render(request, "profiles/profile_list.html", context)


@login_required()
def follow_unfollow_profile(request):
    if request.method == "POST":
        my_profile = Profile.objects.get(user=request.user)
        pk = request.POST.get("profile_pk")
        obj = Profile.objects.get(pk=pk)
        if obj.user in my_profile.following.all():
            my_profile.following.remove(obj.user)
        else:
            my_profile.following.add(obj.user)
        my_profile.save()
        return redirect(request.META.get("HTTP_REFERER"))
    return redirect("profiles:all-profiles-view")


@login_required()
def profile_subs_view(request):
    profile = Profile.objects.get(user=request.user)
    subs = profile.following.all()
    context = {
        "q_set": subs,
    }
    return render(request, "profiles/my_subscriptions.html", context)


class ProfilesDetailView(LoginRequiredMixin, DetailView):
    model = Profile
    template_name = "profiles/detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # user = User.objects.get(username__iexact=self.request.user)
        # profile = Profile.objects.get(user=user)
        profile = Profile.objects.get(user=self.request.user)
        rel_r = Relationship.objects.filter(sender=profile)
        rel_s = Relationship.objects.filter(receiver=profile)
        rel_receiver = []
        rel_sender = []
        for item in rel_r:
            rel_receiver.append(item.receiver.user)
        for item in rel_s:
            rel_sender.append(item.sender.user)
        context["rel_receiver"] = rel_receiver
        context["rel_sender"] = rel_sender
        context["posts"] = self.get_object().get_all_authors_posts()
        context["len_posts"] = True if len(self.get_object().get_all_authors_posts()) > 0 else False
        view_profile = self.get_object()
        if view_profile.user in profile.following.all():
            follow = True
        else:
            follow = False
        context["follow"] = follow
        return context


class ProfilesListView(LoginRequiredMixin, ListView):
    model = Profile
    template_name = "profiles/profile_list.html"

    def get_queryset(self):
        q_set = Profile.objects.get_all_profiles(self.request.user)
        return q_set

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        profile = Profile.objects.get(user=self.request.user)
        rel_r = Relationship.objects.filter(sender=profile)
        rel_s = Relationship.objects.filter(receiver=profile)
        rel_receiver = []
        rel_sender = []
        for item in rel_r:
            rel_receiver.append(item.receiver.user)
        for item in rel_s:
            rel_sender.append(item.sender.user)
        context["rel_receiver"] = rel_receiver
        context["rel_sender"] = rel_sender
        context["is_empty"] = False
        if len(self.get_queryset()) == 0:
            context["is_empty"] = True
        return context


@login_required()
def send_invitation(request):
    if request.method == "POST":
        pk = request.POST.get("profile_pk")
        user = request.user
        sender = Profile.objects.get(user=user)
        receiver = Profile.objects.get(pk=pk)
        rel = Relationship.objects.create(sender=sender, receiver=receiver, status="send")
        return redirect(request.META.get("HTTP_REFERER"))
    return redirect("profiles:my-profile-view")


@login_required()
def remove_from_friends(request):
    if request.method == 'POST':
        pk = request.POST.get('profile_pk')
        user = request.user
        sender = Profile.objects.get(user=user)
        receiver = Profile.objects.get(pk=pk)
        rel = Relationship.objects.get(
            (Q(sender=sender) & Q(receiver=receiver)) | (Q(sender=receiver) & Q(receiver=sender))
        )
        rel.delete()
        return redirect(request.META.get('HTTP_REFERER'))
    return redirect('profiles:my-profile-view')


@login_required()
def search_result(request):
    if request.is_ajax():
        result = None
        name = request.POST.get("name")
        qs = Profile.objects.filter(Q(first_name__icontains=name) | Q(last_name__icontains=name))
        if len(qs) > 0 and len(name) > 0:
            data = []
            for profile in qs:
                item = {
                    "pk": profile.pk,
                    "name": profile.first_name,
                    "last_name": profile.last_name,
                    "avatar": str(profile.avatar.url),
                    "slug": profile.slug,
                }
                data.append(item)
            result = data
        else:
            result = "No profiles found..."
        return JsonResponse({"data": result})
    return JsonResponse({})

profiles/templates/profiles/detail.html
{% extends "base.html" %}

{% block title %}
profile details
{% endblock title %}

{% block content %}
<div class="ui grid">
    <br>
    <div class="row">
        <div class="four wide column">
            <img class="ui medium rounded image" src="{{ object.avatar.url }}">
            <h1>{{ object.user }}</h1>
            <div class="ui vertical fluid menu">
                <div class="item">
                    Posts
                    <div class="ui label">{{ object.get_post_no }}</div>
                </div>
                <div class="item">
                    Likes given
                    <div class="ui label">{{ object.get_likes_given_no }}</div>
                </div>
                <div class="item">
                    Likes received
                    <div class="ui label">{{ object.get_likes_received_no }}</div>
                </div>
                <div class="item">
                    Friends
                    <div class="ui label">{{ object.get_friends_number }}</div>
                </div>
            </div>

            {% if object.user not in rel_receiver and object.user not in rel_sender %}
                <form action="{% url "profiles:send-invite" %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="profile_pk" value={{object.pk}}>
                    <button type="submit" class="ui positive basic button mb-5 w-big"><i class="plus square icon"></i>Add to friends</button>
                </form>
            {% endif %}

            {% if object.user in rel_receiver and request.user not in object.friends.all %}
                <button class="ui disabled button mb-5 w-big"><i class="user icon"></i>Waiting for approval</button>
            {% endif %}

            {% if request.user in object.friends.all %}
                <form action="{% url "profiles:remove-friend" %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="profile_pk" value={{object.pk}}>
                    <button type="submit" class="ui negative basic button mb-5 w-big"><i class="minus square icon"></i>Remove from friends</button>
                </form>
            {% endif %}
            {% if follow %}
                    <form action="{% url "profiles:follow-unfollow-view" %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="profile_pk" value={{object.pk}}>
                    <button type="submit" class="ui negative basic button mb-5 w-big"><i class="minus square icon"></i>Unfollow</button>
                </form>
            {% else %}
                    <form action="{% url "profiles:follow-unfollow-view" %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="profile_pk" value={{object.pk}}>
                    <button type="submit" class="ui positive basic button mb-5 w-big"><i class="plus square icon"></i>Follow</button>
                </form>
            {% endif %}
        </div>
        <div class="twelve wide column">
            {% if len_posts %}
                {% for post in posts %}
                    <div class="segment ui fluid">
                        <img class="ui medium rounded image" src="{{ post.image.url }}">
                        <br>
                        {{ post.content }}
                    </div>
                {% endfor %}
            {% else %}
                <h1>This user has no posts yet!</h1>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

profiles/templates/profiles/my_invites.html
{% extends "base.html" %}

{% block title %}
    my invites
{% endblock title %}

{% block content %}

    {% if is_empty %}
        <h1>No invites here!</h1>
    {% endif %}

    {% for obj in  q_set %}
        <div class="ui segment">
            <div class="ui grid">
                <div class="row">
                    <div class="three wide column">
                        <img class="ui small circilar image" src="{{obj.avatar.url}}">
                    </div>
                    <div class="thirteen wide column">
                        <h3>{{ obj.user }}</h3>
                        <p>{{ obj.bio }}</p>
                        <a href="{{ obj.get_absolute_url }}"><button class="ui primary button w-big mb-5">View profile</button></a>

                        <form action="{% url "profiles:accept-invite" %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="profile_pk" value="{{ obj.pk }}">
                            <button type="submit" class="ui positive basic button w-big mb-5">
                                <i class="check icon"></i>
                                Accept
                            </button>
                        </form>

                        <form action="{% url "profiles:reject-invite" %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="profile_pk" value="{{ obj.pk }}">
                            <button type="submit" class="ui negative basic button w-big mb-5">
                                <i class="close icon"></i>
                                Reject
                            </button>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    {% endfor %}

{% endblock content %}

profiles/templates/profiles/my_subscriptions.html
{% extends 'base.html' %}

{% block title %}
my subscriptions
{% endblock title %}

{% block content %}

    {% if not q_set %}
        <h1>You have no subscriptions :(</h1>
    {% endif %}

    {% for obj in q_set %}
        <div class="ui segment">
            <div class="ui grid">
                <div class="row">
                    <div class="three wide column">
                        <img class="ui small circular image" src={{ obj.profile.avatar.url }}>
                    </div>
                    <div class="thirteen wide column">
                        <h3>{{ obj.profile.user }}</h3>
                        <p>{{ obj.profile.bio }}</p>
                        <a href="{{ obj.profile.get_absolute_url }}"><button class="ui primary button mb-5">View profile</button></a>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock content %}

profiles/templates/profiles/myprofile.html
{% extends "base.html" %}

{% block title %}
my profile
{% endblock title %}

{% block content %}

<!--MODAL -->
<div class="ui modal my_modal">
  <i class="close icon"></i>
  <div class="image content">
    <div class="ui medium image">
      <img src="{{ profile.avatar.url }}">
    </div>
    <div class="description my_modal">
      <div class="ui header">Update your profile</div>
        <form action="" method="POST" class="ui form" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
    </div>
  </div>
  <div class="actions">
    <button type="submit" class="ui positive right labeled icon button">
      Update
      <i class="checkmark icon"></i>
    </button>
        </form>
  </div>
</div>

<div class="ui segment">
    {% if confirm %}
        <div class="ui green message">Updated!</div>
    {% endif %}
    <h3>my profile: {{request.user}}</h3>
    <div class="ui grid">
        <div class='row'>
            <div class='six wide column'>
                <img class="ui medium rounded image" src={{profile.avatar.url}}>
                <div class="row mt-5">
                    <button class='ui primary button' id='modal-btn'>Update your profile</button>
                </div>
            </div>
            <div class="ten wide column">
                <table class="ui table">
                    <tbody>
                        <tr>
                            <td>username</td>
                            <td>{{profile.user}}</td>
                        </tr>
                        <tr>
                            <td>first name</td>
                            <td>{{profile.first_name}}</td>
                        </tr>
                        <tr>
                            <td>last name</td>
                            <td>{{profile.last_name}}</td>
                        </tr>
                        <tr>
                            <td>bio</td>
                            <td>{{profile.bio}}</td>
                        </tr>
                        <tr>
                            <td>country</td>
                            <td>{{profile.country}}</td>
                        </tr>
                        <tr>
                            <td>number of friends</td>
                            <td>{{profile.get_friends_number}}</td>
                        </tr>
                        <tr>
                            <td>friends</td>
                            <td>
                                <ul>
                                    {% for friend in profile.get_friends %}
                                        <li>{{friend}}</li>
                                    {% endfor %}
                                </ul>
                            </td>
                        </tr>
                        <tr>
                            <td>number of posts</td>
                            <td>{{profile.get_post_no}}</td>
                        </tr>
                        <tr>
                            <td>number of given likes</td>
                            <td>{{profile.get_likes_given_no}}</td>
                        </tr>
                        <tr>
                            <td>number of received likes</td>
                            <td>{{profile.get_likes_received_no}}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

profiles/templates/profiles/profile_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
all profiles
{% endblock title %}

{% block content %}

    {% if is_empty %}
        <h1>No profiles to interact with</h1>
    {% endif %}

    <div class="ui center aligned basic segment mt-15">
        <form action="javascript:void(0);" id="search-form" class="ui icon input" autocomplete="off">
            {% csrf_token %}
            <input type="text" id="search-input" placeholder="First name or last name...">
            <i class="search icon"></i>
          <div class="results"></div>
        </form>
    </div>

    <div class="not-visible" id="results-box">
    </div>

    {% for obj in object_list %}
        <div class="ui segment">
            <div class="ui grid">
                <div class="row">
                    <div class="three wide column">
                        <img class="ui small circular image" src={{obj.avatar.url}}>
                    </div>
                    <div class="thirteen wide column">
                        <h3>{{obj.user}} | {{obj.first_name}} {{obj.last_name}}</h3>
                        <p>{{obj.bio}}</p>
                        <a href="{{ obj.get_absolute_url }}"><button class="ui primary button mb-5">See profile</button></a>

                        {% if obj.user not in rel_receiver and obj.user not in rel_sender %}
                            <form action="{% url "profiles:send-invite" %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="profile_pk" value={{obj.pk}}>
                                <button type="submit" class="ui positive basic button mb-5 w-big"><i class="plus square icon"></i>Add to friends</button>
                            </form>
                        {% endif %}

                        {% if obj.user in rel_receiver and request.user not in obj.friends.all %}
                            <button class="ui disabled button mb-5 w-big"><i class="user icon"></i>Waiting for approval</button>
                        {% endif %}

                        {% if request.user in obj.friends.all %}
                            <form action="{% url "profiles:remove-friend" %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="profile_pk" value={{obj.pk}}>
                                <button type="submit" class="ui negative basic button mb-5 w-big"><i class="minus square icon"></i>Remove from friends</button>
                            </form>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock content %}

profiles/templates/profiles/to_invite_list.html
{% extends "base.html" %}

{% block title %}
    invite friends
{% endblock title %}

{% block content %}

    {% if is_empty %}
        <h1>No profiles to interact with</h1>
    {% endif %}

    {% for obj in q_set %}
        <div class="ui segment">
            <div class="ui grid">
                <div class="row">
                    <div class="three wide column">
                        <img class="ui small circular image" src={{obj.avatar.url}}>
                    </div>
                    <div class="thirteen wide column">
                        <h3>{{obj.user}}</h3>
                        <p>{{obj.bio}}</p>
                        <a href="{{ obj.get_absolute_url }}"><button class="ui primary button mb-5">See profile</button></a>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock content %}