djangogramm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", home_view, name="home-view"),
    path('accounts/', include('allauth.urls')),
    path("profiles/", include("profiles.urls", namespace="profiles")),
    path("posts/", include("posts.urls", namespace="posts")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

posts/urls.py
from django.urls import path
from .views import (post_comment_create_and_list_view, like_dislike_posts,
                    PostDeleteView, PostUpdateView, posts_of_following_profiles)


app_name = "posts"
urlpatterns = [
    path("", post_comment_create_and_list_view, name="main-post-view"),
    path("following/", posts_of_following_profiles, name="follow-post-view"),
    path("liked/", like_dislike_posts, name="like-post-view"),
    path("<pk>/delete/", PostDeleteView.as_view(), name="post-delete"),
    path("<pk>/update/", PostUpdateView.as_view(), name="post-update"),
]

profiles/urls.py
from django.urls import path
from .views import (
    my_profile_view, invites_received_view, invite_profiles_list_view, ProfilesListView, follow_unfollow_profile,
    ProfilesDetailView, send_invitation, accept_invitation, reject_invitation, remove_from_friends, profile_subs_view,
    search_result
)


app_name = "profiles"

urlpatterns = [
    path("", ProfilesListView.as_view(), name="all-profiles-view"),
    path("search/", search_result, name="search"),
    path("myprofile/", my_profile_view, name="my-profile-view"),
    path("my-invites/", invites_received_view, name="my-invites-view"),
    path("to-invite/", invite_profiles_list_view, name="invite-profiles-view"),
    path("send-invite/", send_invitation, name="send-invite"),
    path("remove-friend/", remove_from_friends, name="remove-friend"),
    path("switch_follow/", follow_unfollow_profile, name="follow-unfollow-view"),
    path("my-subscriptions/", profile_subs_view, name="my-subscriptions"),
    path("<slug>/", ProfilesDetailView.as_view(), name="profiles-detail-view"),
    path("my-invites/accept/", accept_invitation, name="accept-invite"),
    path("my-invites/reject/", reject_invitation, name="reject-invite"),
]

templates/main/home.html
{% extends "base.html" %}

{% block title %}
    home
{% endblock title %}

{% block content %}
    {{ hello }}
    <br>
    {{ user }}
{% endblock content %}

{% block scripts %}
    <script>
    $(document).ready(function (){
        console.log("It is OK")
    })
    </script>
{% endblock scripts %}

templates/main/navbar.html
{% url "home-view" as path_to_home %}
{% url "posts:main-post-view" as path_to_posts %}
{% url "posts:follow-post-view" as path_to_following %}
{% url "profiles:my-profile-view" as path_to_my_profile %}
{% url "profiles:my-invites-view" as path_to_my_invites %}
{% url "profiles:invite-profiles-view" as path_to_invites %}
{% url "profiles:all-profiles-view" as path_to_all_profiles %}
{% url "profiles:my-subscriptions" as path_to_my_subs %}


<div class="ui inverted menu nav mb-5">
  <div class="ui container">
    <a href="{{ path_to_posts }}" class="{% if request.path == path_to_posts %}active{% endif %} item">
        <h3>DjangoGramm</h3>
    </a>
    {% if request.user.is_authenticated %}
    <a href="{{ path_to_following }}" class="{% if request.path == path_to_following %}active{% endif %} item">
        <h4>Following</h4>
    </a>
    {% endif %}

    <div class="right menu">
        {% if request.user.is_authenticated %}
        <div class="item">
            <div class="ui dropdown purple button"> Friends/Subs
                <i class="dropdown icon"></i>
                <div class="menu">
                    <a href="{{ path_to_all_profiles }}" class="{% if request.path == path_to_all_profiles %}active{% endif %} item">
                        All Profiles
                    </a>
                    <a href="{{ path_to_my_subs }}" class="{% if request.path == path_to_my_subs %}active{% endif %} item">
                        My subscriptions
                    </a>
                    <a href="{{ path_to_invites }}" class="{% if request.path == path_to_invites %}active{% endif %} item">
                        Send Friend Invites
                    </a>
                    <a href="{{ path_to_my_invites }}" class="{% if request.path == path_to_my_invites %}active{% endif %} item">
                        Received Friends Invites &nbsp; <div class="ui purple horizontal label">{{ invites_num }}</div>
                    </a>
                </div>
             </div>
        </div>

            <a href="{{ path_to_my_profile }}" class="{% if request.path == path_to_my_profile %}active{% endif %} item">
                <img class="ui avatar image" src="{{ picture.url }}"> &nbsp;
                {{ request.user }}
            </a>

            <a href="{% url "account_logout" %}" class="ui item">
                Sign Out
            </a>
        {% else %}
        <a href="{% url "account_login" %}" class="ui item">
                Sign In
            </a>
        {% endif %}
    </div>
  </div>
</div>